/*DROP TABLE TA_EMPLEADO;
DROP TABLE TA_CLIENTE;
DROP TABLE TA_VENTA;
DROP TABLE TA_LINEA_VENTA;
DROP TABLE TA_PRODUCTO;
DROP TABLE TA_CATEGORIA;*/


CREATE TABLE TA_EMPLEADO(
    NUM_EMPLEADO            NUMBER(10),
    NOMBRE                  VARCHAR2(100),
    APELLIDOS               VARCHAR2(100),
    EMAIL                   VARCHAR2(100),
    CUENTA_CORRIENTE        VARCHAR2(24),
    PASS                    VARCHAR(8),
    
CONSTRAINT PK_TA_EMPLEADO PRIMARY KEY (NUM_EMPLEADO),
CONSTRAINT NN_TA_EMP_NOM CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_TA_EMP_APEL CHECK (APELLIDOS IS NOT NULL),
CONSTRAINT CK_TA_EMP_EMA CHECK (EMAIL LIKE '%@%'),
CONSTRAINT CK_TA_EMP_CUE CHECK (CUENTA_CORRIENTE LIKE 'ES%'),
CONSTRAINT CK_TA_EMP_PAS CHECK (PASS NOT LIKE '% %')
);

CREATE TABLE TA_CLIENTE(
    DNI                     VARCHAR2(10),
    NOMBRE                  VARCHAR2(100),
    APELLIDOS               VARCHAR2(100),
    EMAIL                   VARCHAR2(100),
    DIRECCION               VARCHAR2(100),
    FECHA_ALTA              DATE,
    
CONSTRAINT PK_TA_CLIENTE PRIMARY KEY (DNI),
CONSTRAINT NN_TA_EMP_NOM2 CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_TA_EMP_APEL2 CHECK (APELLIDOS IS NOT NULL),
CONSTRAINT CK_TA_EMP_EMA2 CHECK (EMAIL LIKE '%@%')
);

CREATE TABLE TA_VENTA(
    ID_VENTA                NUMBER(10),
    FECHA                   DATE,
    EMPLEADO                NUMBER(10),
    CLIENTE                 VARCHAR2(10),

CONSTRAINT PK_TA_VENTA PRIMARY KEY (ID_VENTA),
CONSTRAINT NN_TA_VEN_FEC CHECK (FECHA IS NOT NULL),
CONSTRAINT NN_TA_VEN_EMP CHECK (EMPLEADO IS NOT NULL)
);

CREATE TABLE TA_LINEA_VENTA(
    ID_VENTA                NUMBER(10),
    ID_LINEA                NUMBER(10),
    CANTIDAD                NUMBER(6),
    PRODUCTO                NUMBER(10),
    PRECIO                  NUMBER(10,2),
    
CONSTRAINT PK_TA_LIN_VENT PRIMARY KEY (ID_VENTA, ID_LINEA),
CONSTRAINT NN_TA_LIN_VENT_CANT CHECK (CANTIDAD IS NOT NULL),
CONSTRAINT CK_TA_LIN_VENT_CANT CHECK (CANTIDAD > 0),
CONSTRAINT NN_TA_LIN_VENT_PROD CHECK (PRODUCTO IS NOT NULL),
CONSTRAINT NN_TA_LIN_VENT_PRE CHECK (PRECIO IS NOT NULL)
);

CREATE TABLE TA_PRODUCTO(
    CUP                     NUMBER(10),
    NOMBRE                  VARCHAR2(100),
    DESCRIPCION             VARCHAR2(4000),
    PVP                     NUMBER(10,2),
    CATEGORIA               NUMBER(10),

CONSTRAINT PK_TA_PRODUCTO PRIMARY KEY (CUP),
CONSTRAINT NN_TA_PROD_NOM CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_TA_PROD_DES CHECK (DESCRIPCION IS NOT NULL),
CONSTRAINT NN_TA_PROD_PVP CHECK (PVP IS NOT NULL),
CONSTRAINT NN_TA_PROD_CAT CHECK (CATEGORIA IS NOT NULL)
);

CREATE TABLE TA_CATEGORIA(
    ID_CATEGORIA            NUMBER(10),
    NOMBRE                  VARCHAR2(100),
    DESCRIPCION             VARCHAR2(4000),
    
CONSTRAINT PK_TA_CATEGORIA PRIMARY KEY (ID_CATEGORIA),
CONSTRAINT NN_TA_CAT_NOM CHECK (NOMBRE IS NOT NULL),
CONSTRAINT NN_TA_CAT_DES CHECK (DESCRIPCION IS NOT NULL)
);

CREATE SEQUENCE SEQ_TA_VENTA
START WITH 100
INCREMENT BY 1;

CREATE SEQUENCE SEQ_TA_LINEA_VENTA
START WITH 1
INCREMENT BY 1;

--El cliente Jesús Casanova realiza la compra de un Macbook Pro modelo Touch Bar de 256 GB de disco duro. Es atendido por el empleado Miguel Campos. Recuerda que la compra de un cliente implica una inserción en la tabla TA_VENTA, y una por cada producto diferente en la tabla TA_LINEA_VENTA


INSERT INTO TA_VENTA
VALUES (SEQ_TA_VENTA.NEXTVAL, TO_DATE('13/02/2020', ('DD/MM/YYYY')), 2, '12345678A');

INSERT INTO TA_LINEA_VENTA
VALUES (SEQ_TA_LINEA_VENTA.NEXTVAL, 1, 1, 3, 1999);

--El cliente Rafael Villar se da de alta. Su email es rafael.villar@correo.com, su dirección es Calle Rue del Percebe 13 y su fecha de alta es hoy mismo.

INSERT INTO TA_CLIENTE
VALUES ('63651452F', 'Rafael', 'Villar', 'rafael.villar@correo.com', 'Calle Rue del Percebe 13', TO_DATE('13/02/2020', ('DD/MM/YYYY')));

--Tras darse de alta, Rafael Villar adquiere un Apple Wath Nike+. Le atiende el empleado Ángel Naranjo.

INSERT INTO TA_VENTA
VALUES (SEQ_TA_VENTA.NEXTVAL, TO_DATE('13/02/2020', ('DD/MM/YYYY')), 2, '63651452F');

INSERT INTO TA_LINEA_VENTA
VALUES (SEQ_TA_LINEA_VENTA.NEXTVAL, 9, 1, 3, 429);

