CREATE TABLE NFX_CLIENTES(
    ID_CLIENTE           NUMBER(10),
    NOMBRE              VARCHAR2(25),
    APELLIDOS           VARCHAR2(25),
    DIRECCION           VARCHAR2(50),
    TELEFONO            NUMBER(9),
    CP                  NUMBER(5),
    POBLACION           VARCHAR2(25),
    PROVINCIA           VARCHAR2(25),
    EMAIL               VARCHAR2(320),
    
    CONSTRAINT PK_NFX_CLIENTES PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT NN_NFX_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_NFX_APELLIDOS CHECK (APELLIDOS IS NOT NULL),
    CONSTRAINT NN_NFX_EMAIL CHECK (EMAIL IS NOT NULL),
    CONSTRAINT NN_NFX_CP CHECK (CP IS NOT NULL)
    
);

CREATE TABLE NFX_TITULOS(
    ID_TITULO           NUMBER(10),
    TIPO                VARCHAR2(30),
    GENERO              VARCHAR2(100),
    ANIO                NUMBER(4),
    DURACION            NUMBER,
    FECHA_ALTA          DATE,
    FECHA_FIN           DATE,
    DISPONIBILIDAD      NUMBER(3),
    PRECIO_ALQUILER     NUMBER,
    
    CONSTRAINT PK_NFX_TITULOS PRIMARY KEY (ID_TITULO),
    CONSTRAINT CK_NFX_ALQUILER CHECK (PRECIO_ALQUILER>0)
);

CREATE TABLE NFX_ALQUILERES(
    ID_ALQUILER         NUMBER(10),
    ID_CLIENTE          NUMBER(10),
    ID_TITULO           NUMBER(10),
    FECHA_ALQUILER      DATE,
    DURACION            NUMBER,
    IMPORTE             NUMBER,
    
    CONSTRAINT PK_NFX_ALQUILERES PRIMARY KEY (ID_ALQUILER),
    CONSTRAINT CK_NFX_IMPORTE CHECK (IMPORTE>0)
);
ALTER TABLE NFX_ALQUILERES
ADD CONSTRAINT FK_NFX_ALQUILERES_NFX_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES NFX_CLIENTES(ID_CLIENTE);
/*
DROP TABLE NFX_CLIENTES;
DROP TABLE NFX_TITULOS;
DROP TABLE NFX_ALQUILERES;