ALTER USER MFARJONA IDENTIFIED BY "2875";

--ALUMNOS(NUM_ALUM, NOMBRE, APELLIDO1, APELIDO2, EMAIL)

CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE
);
--DATE DEFAULT SYSDATE. FECHA POR DEFECTO ES LA FECHA DEL SISTEMA, SI NO SE RELLENA EL CAMPO COGE ESA FECHA, PUEDES PONER OTRA

DROP TABLE SAM01_alumnos;--BORRAR DATOS DE LA TABLA
FLASHBACK TABLE SAM01_alumnos TO BEFORE DROP;--RECUPERAR DATOS DE LA TABLA A ANTES DE ELIMINARLA, HAY QUE PONER UN CUANDO

--AÑADIR UNA RESTRICCION DE CLAVE PRIMARIA
--1 ESTO NO EN PRINCIPIO
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8) CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY,
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE
);
--2 ESTA ES LA QUE LE GUSTA A LUISMI
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM)
);

--RESTRICCION DE UNICIDAD, ESTO QUIERE DECIR QUE LA FILA EMAIL NO PUEDE ESTAR REPETIDA, NO PUEDE HABERLA 2 VECES, NULL NO ENTRA
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL)
);

--RESTRICCION DE OBLIGATORIEDAD
--1 NO
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8) NOT NULL,
    NOMBRE              VARCHAR2(100) NOT NULL,
    APELLIDO1           VARCHAR2(100) NOT NULL,
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE NOT NULL,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL)
);
--2 GUSTA
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL),
    CONSTRAINT NN_SAM01_ALUMNOS_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_APELLIDO1 CHECK (APELLIDO1 IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_FECHA_NAC CHECK (FEHCA_NACIMIENTO IS NOT NULL)
);

--RESTRICCIONES DE VALIDACION
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL),
    CONSTRAINT NN_SAM01_ALUMNOS_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_APELLIDO1 CHECK (APELLIDO1 IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_FECHA_NAC CHECK (FEHCA_NACIMIENTO IS NOT NULL),
    CONSTRAINT CK_SAM01_ALUMNOS_NUMlALUM_POS CHECK (NUM_ALUM > 0),
    CONSTRAINT CK_SAM01_ALUMNOS_MAYOR CHECK (EXTRACT(YEAR FROM FECHA_ALTA) - EXTRACT(YEAR FROM FEHCA_NACIMIENTO)>=18)
);

--ALTERAR TABLA PARA PONER CLAVE EXTERNA
ALTER TABLE SAM01_NOTAS
ADD CONSTRAINT FK_SAM01_NOTAS_SAM01_ALUMNOS FOREIGN KEY (NUM_ALUM) REFERENCES SAM01_ALUMNOS(NUM_ALUM)
ON DELETE SET NULL/*CASCADE, SET DEFAULT, NOTHING*/;