CREATE TABLE LFP_ESTADIOS(
    ID                      NUMBER(10),
    NOMBRE                  VARCHAR2(20),
    CAPACIDAD               NUMBER(10),
    DIRECCION               VARCHAR2(30),
    CP                      NUMBER(5),
    PROVINCIA               VARCHAR(15),
    TELEFONO                NUMBER(9),
    FEC_INAUGURACION        DATE,
    PROPIETARIO             VARCHAR2(50),
    DIMENSIONES             VARCHAR2(15),
    OTRAS_INSTALACIONES     VARCHAR2(200),
    LOCALIDAD               VARCHAR2(35),
    
    CONSTRAINT PK_LFP_ESTADIOS PRIMARY KEY (ID)
);                          
                            
CREATE TABLE LFP_EQUIPOS(   
    ID                      NUMBER(10),
    NOMBRE                  VARCHAR2(20),
    NOMBRE_OFICIAL          VARCHAR2(50),
    DIRECCION               VARCHAR2(30),
    CP                      NUMBER(5),
    PROVINCIA               VARCHAR2(15),
    PAIS                    VARCHAR2(20),
    URL_INTERNET            VARCHAR2(300),
    EMAIL                   VARCHAR2(320),
    NUMERO_PEÑAS            NUMBER(9),
    TELEFONO                NUMBER(9),
    FAX                     VARCHAR2(320),
    OTRAS_SECCIONES         VARCHAR2(320),
    FECHA_FUNDACION         DATE,
    HISTORIA                VARCHAR2(500),
    HIMNO                   VARCHAR2(50),
    ESTADIO                 VARCHAR(35),
    LOCALIDAD               VARCHAR2(35),
    
    CONSTRAINT PK_LFP_EQUIPOS PRIMARY KEY (ID)
);

CREATE TABLE LFP_JUGADORES(
    ID                      NUMBER(10),
    NOMBRE_FUTBOLISTICO     VARCHAR2(35),
    NOMBRE                  VARCHAR(20),
    APELLIDOS               VARCHAR2(50),
    FECHA_NACIMIENTO        DATE,
    LUGAR_NACIMIENTO        VARCHAR(35),       
    PROVINCIA               VARCHAR(40),        
    PAIS                    VARCHAR2(20),
    PIE                     NUMBER(3,1),
    DEMARCACION             VARCHAR2(20),
    ALTURA                  NUMBER(3,2),
    PESO                    NUMBER(3,1),
    EQUIPO                  VARCHAR2(20),
    CANTERA                 VARCHAR2(30),
    INTERNACIONAL           VARCHAR2(2),
    HISTORIAL               VARCHAR2(500),
    REPRESENTANTE           VARCHAR(30),
    PAIS_NACIONALIDAD       VARCHAR2(30),    
    RETIRADO                VARCHAR(2),
    
    CONSTRAINT PK_LFP_JUGADORES PRIMARY KEY (ID)
);

CREATE TABLE LFP_PAISES(
    ID                      NUMBER(10),
    PAIS                    VARCHAR2(20),
    ABREVIATURA             VARCHAR2(3),
    
    CONSTRAINT PK_LFP_PAISES PRIMARY KEY (ID)
);

CREATE TABLE LFP_DEMARCACION(
    ID                       NUMBER(10),   
    NOMBRE                   VARCHAR(20),   
    
    CONSTRAINT PK_LFP_DEMARCACION PRIMARY KEY (ID)
);

CREATE TABLE LFP_PROVINCIAS(
    ID                       NUMBER(10),   
    NOMBRE                   VARCHAR(20),   
    
    CONSTRAINT PK_LFP_PROVINCIAS PRIMARY KEY (ID)
);

CREATE TABLE LFP_REPRESENTANTES(
    ID                       NUMBER(10),   
    NOMBRE                   VARCHAR(20),   
    
    CONSTRAINT PK_LFP_REPRESENTANTES PRIMARY KEY (ID)
);
ALTER TABLE LFP_EQUIPOS
ADD CONSTRAINT FK_LFP_EQUIPOS_EST FOREIGN KEY (ID) REFERENCES LFP_ESTADIOS;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_EQ FOREIGN KEY (ID) REFERENCES LFP_EQUIPOS;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_CAN FOREIGN KEY (ID) REFERENCES LFP_EQUIPOS;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_PAI FOREIGN KEY (ID) REFERENCES LFP_PAISES;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_DEM FOREIGN KEY (ID) REFERENCES LFP_DEMARCACION;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_PRO FOREIGN KEY (ID) REFERENCES LFP_PROVINCIAS;

ALTER TABLE LFP_JUGADORES
ADD CONSTRAINT FK_LFP_JUGADORES_REP FOREIGN KEY (ID) REFERENCES LFP_REPRESENTANTES;
/*
DROP TABLE LFP_ESTADIOS;
DROP TABLE LFP_EQUIPOS;
DROP TABLE LFP_JUGADORES;
DROP TABLE LFP_PAISES;
DROP TABLE LFP_DEMARCACION;
DROP TABLE LFP_PROVINCIAS;
DROP TABLE LFP_REPRESENTANTES;