--ALUMNOS(NUM_ALUM, NOMBRE, APELLIDO1, APELIDO2, EMAIL)

CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE
);
--DATE DEFAULT SYSDATE. FECHA POR DEFECTO ES LA FECHA DEL SISTEMA, SI NO SE RELLENA EL CAMPO COGE ESA FECHA, PUEDES PONER OTRA

DROP TABLE SAM01_alumnos;--BORRAR DATOS DE LA TABLA
FLASHBACK TABLE SAM01_alumnos TO BEFORE DROP;--RECUPERAR DATOS DE LA TABLA A ANTES DE ELIMINARLA, HAY QUE PONER UN CUANDO

--AÑADIR UNA RESTRICCION DE CLAVE PRIMARIA
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM)
);

--RESTRICCION DE UNICIDAD, ESTO QUIERE DECIR QUE LA FILA EMAIL NO PUEDE ESTAR REPETIDA, NO PUEDE HABERLA 2 VECES, NULL NO ENTRA
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL)
);

--RESTRICCION DE OBLIGATORIEDAD
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL),
    CONSTRAINT NN_SAM01_ALUMNOS_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_APELLIDO1 CHECK (APELLIDO1 IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_FECHA_NAC CHECK (FEHCA_NACIMIENTO IS NOT NULL)
);

--RESTRICCIONES DE VALIDACION
CREATE TABLE SAM01_ALUMNOS (
    NUM_ALUM            NUMBER(8),
    NOMBRE              VARCHAR2(100),
    APELLIDO1           VARCHAR2(100),
    APELLIDO2           VARCHAR2(100),
    EMAIL               VARCHAR2(320),
    FEHCA_NACIMIENTO    DATE,
    FECHA_ALTA          DATE DEFAULT SYSDATE,
    CONSTRAINT PK_SAM01_ALUMNOS PRIMARY KEY (NUM_ALUM),
    CONSTRAINT UK_SAM01_ALUMNOS UNIQUE (EMAIL),
    CONSTRAINT NN_SAM01_ALUMNOS_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_APELLIDO1 CHECK (APELLIDO1 IS NOT NULL),
    CONSTRAINT NN_SAM01_ALUMNOS_FECHA_NAC CHECK (FEHCA_NACIMIENTO IS NOT NULL),
    CONSTRAINT CK_SAM01_ALUMNOS_NUMlALUM_POS CHECK (NUM_ALUM > 0),
    CONSTRAINT CK_SAM01_ALUMNOS_MAYOR CHECK (EXTRACT(YEAR FROM FECHA_ALTA) - EXTRACT(YEAR FROM FEHCA_NACIMIENTO)>=18)
);

--ALTERAR TABLA PARA PONER CLAVE EXTERNA
ALTER TABLE SAM01_NOTAS
ADD CONSTRAINT FK_SAM01_NOTAS_SAM01_ALUMNOS FOREIGN KEY (NUM_ALUM) REFERENCES SAM01_ALUMNOS(NUM_ALUM);

--POLITICAS DE BORRADO
ON DELETE SET NULL/*CASCADE, SET DEFAULT, NOTHING*/;
ON DELETE CASCADE;
--MODIFICAR TABLAS
--Nombre
ALTER TABLE nombreViejo RENAME TO nombreNuevo;

--AÑADIR Columnas
ALTER TABLE facturas ADD (fecha DATE);
--BORRAR Columnas
ALTER TABLE facturas DROP (fecha);
--MODIFICAR Columnas
ALTER TABLE facturas MODIFY(fecha TIMESTAMP);
/*Incrementar precisión o anchura de los tipos de datos
Solo se puede reducir la anchura si la anchura máxima de un campo si esa columna posee nulos en todos los registros, o todos los valores existentes tienen un tamaño menor o igual a la nueva anchura.
Se puede pasar de CHAR a VARCHAR2 y viceversa (si no se modifica la anchura)
Se puede pasar de DATE a TIMESTAMP y viceversa
Cualquier otro cambio solo es posible si la tabla está vacía
Si, a través de este comando, modificamos el valor de la propiedad DEFAULT de una tabla, dicho cambio solo tendrá efecto en la inserción de nuevas filas.*/
--RENOMBRAR Columnas
ALTER TABLE facturas RENAME COLUMN fecha TO fechaYhora;

--TABLAS SIN USAR
ALTER TABLE personas SET UNUSED (n_seguridad_social, DNI);
SELECT * FROM USER_UNUSED_COL_TABS;
ALTER TABLE personas DROP UNUSED COLUMNS;

--BORRAR RESTRICCIONES
ALTER TABLE SAM01_ALUMNOS
DROP CONSTRAINT CK_SAM01_ALUMNOS_MAYOR;

--CREAR SECUENCIA
CREATE SEQUENCE SECUENCUA
START WITH 1
INCREMENT BY 1;
--USAR SECUENCIA
SELECT SECUENCUA.NEXTVAL FROM DUAL;

--MODIFICAR DATOS
UPDATE clientes
SET provincia='Ourense'
WHERE provincia='Orense';

UPDATE productos SET precio=precio*1.16;
--si no se pone el where modificas todos los datos de la columna
--SI AL ACTUALIZAR UNA TABLA QUIERO GARANTIZAR QUE SOLO SE MODIGICA UNA FILA EN LA CONDICION DEL WHERE TENDRA QUE COLOCARSE LA CLAVE PRIMARIA DE LA TABLA

--DELETE TABLAS
DELETE FROM empleados WHERE seccion=23;

--CREAR INDICES
CREATE INDEX nombre_completo
ON clientes (apellido1, apellido2, nombre);

--CREAR SINÓNIMOS
CREATE SYNONYM nombre FOR objeto;
