CREATE TABLE LIBROS(
    ISBN                VARCHAR2(13),
    TITULO              VARCHAR2(50),
    DNI_AUTOR           VARCHAR2(9),
    COD_GENERO          NUMBER(3),
    COD_EDITORIAL       NUMBER(10),
    CONSTRAINT PK_LIBROS PRIMARY KEY (ISBN),
    CONSTRAINT NN_LIBROS_TITULO CHECK (TITULO IS NOT NULL),
    CONSTRAINT NN_LIBROS_DNI_AUTOR CHECK (DNI_AUTOR IS NOT NULL),
    CONSTRAINT NN_LIBROS_COD_GENERO CHECK (COD_GENERO IS NOT NULL),
    CONSTRAINT NN_LIBROS_COD_EDITORIAL CHECK (COD_EDITORIAL IS NOT NULL)
);

CREATE TABLE AUTORES(
    DNI                 VARCHAR2(9),
    NOMBRE              VARCHAR2(35),
    NACIONALIDAD        VARCHAR2(30),
    CONSTRAINT PK_AUTORES_DNI PRIMARY KEY (DNI),
    CONSTRAINT NN_AUTORES_NOMBRE CHECK (NOMBRE IS NOT NULL)
);

CREATE TABLE EDITORIAL(
    COD_EDITORIAL       NUMBER(3),
    NOMBRE              VARCHAR2(40),
    DIRECCION           VARCHAR2(35),
    POBLACION           VARCHAR2(35),
    CONSTRAINT PK_EDITORIAL_COD_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

CREATE TABLE GENERO(
    ID_GENERO           NUMBER(3),
    NOMBRE              VARCHAR2(30),
    DESCRIPCION         VARCHAR2(300),
    CONSTRAINT PK_GENERO_ID_GENERO PRIMARY KEY (ID_GENERO)
);

CREATE TABLE EDICIONES(
    ISBN                VARCHAR2(13),
    FECHA_PUBLICACION   DATE,
    CANTIDAD            NUMBER(3),
    CONSTRAINT PK_EDICIONES_FECHA_PUB PRIMARY KEY (ISBN, FECHA_PUBLICACION),
    CONSTRAINT CK_EDICIONES_CANTIDAD CHECK (CANTIDAD>0)
);