CREATE TABLE JDI_DOCENTES (
	DNI 				VARCHAR2(9),
	NOMBRE		    	VARCHAR2(200),
	DIRECCION			VARCHAR2(200),
	TELEFONO			VARCHAR2(13),
	ANIOINGRESO	    	NUMBER(4) ,
	CONSTRAINT PK_JDI_DOCENTES PRIMARY KEY (DNI),
	CONSTRAINT NN_JDI_DOCENTES_NOMBRE CHECK (NOMBRE IS NOT NULL),
	CONSTRAINT NN_JDI_DOCENTES_TELF CHECK (TELEFONO IS NOT NULL),
    CONSTRAINT CK_JDI_DOCENTES_ANIO CHECK (ANIOINGRESO >= 2000)
);

CREATE TABLE JDI_ACTIVIDADES (
	ID_ACT		    	NUMBER(3),
    NOMBRE		    	VARCHAR2(100),
	DURACION			NUMBER(3),
	CONSTRAINT PK_JDI_ACTIVIDADES PRIMARY KEY (ID_ACT),
	CONSTRAINT NN_JDI_ACTIVIDADES_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT CK_JDI_ACTIVIDADES_DUR CHECK (DURACION >0)
);

CREATE TABLE JDI_ALUMNOS(
    COD_ALUMNO	    	NUMBER(3),	
    NOMBRE		    	VARCHAR2(500),
    TELEFONO			VARCHAR2(12),
    NIVEL				NUMBER(1),
    SEXO                CHAR(1),
    CONSTRAINT PK_JDI_ALUMNOS PRIMARY KEY (COD_ALUMNO),
	CONSTRAINT CK_JDI_ALUMNOS_NIVEL CHECK (NIVEL BETWEEN 0 AND 5),
    CONSTRAINT NN_JDI_ALUMNOS_NOMBRE CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_JDI_ALUMNOS_TELEFONO CHECK (TELEFONO IS NOT NULL),
    CONSTRAINT NN_JDI_ALUMNOS_NIVEL CHECK (NIVEL BETWEEN 0 AND 5),
    CONSTRAINT CK_JDI_ALUMNOS_SEXO CHECK (SEXO IN ('H','M'))
);

CREATE TABLE JDI_ASIGNACION_ACT (
	DNI 				VARCHAR2(9),
	ID_ACT 		    	NUMBER(3),
	DIA_SEMANA			VARCHAR2(20),
	HORA				NUMBER(4),
	CONSTRAINT PK_JDI_ASIGNACION_ACT PRIMARY KEY (DNI, ID_ACT, DIA_SEMANA, HORA)
);

CREATE TABLE JDI_ASISTENCIA_ACT(
	COD_ALUMNO 	    	NUMBER(10),
	ID_ACT 		    	NUMBER(3),
    DNI			        VARCHAR2(9),
    CONSTRAINT PK_JDI_ASISTENCIA_ACT PRIMARY KEY (COD_ALUMNO, ID_ACT)
);

ALTER TABLE JDI_ASIGNACION_ACT
ADD CONSTRAINT FK_JDI_ASIGNACION_JDI_DOCENTES FOREIGN KEY (DNI) REFERENCES JDI_DOCENTES (DNI);
--NO HACER NADA

ALTER TABLE JDI_ASIGNACION_ACT
ADD CONSTRAINT FK_JDI_ASIGNACION_ACT_ACTIVID FOREIGN KEY (ID_ACT) REFERENCES JDI_ACTIVIDADES (ID_ACT) ON DELETE CASCADE;

ALTER TABLE JDI_ASISTENCIA_ACT
ADD CONSTRAINT FK_JDI_ASISTENCIA_ALUMNOS FOREIGN KEY (COD_ALUMNO) REFERENCES JDI_ALUMNOS (COD_ALUMNO) ON DELETE SET NULL;

ALTER TABLE JDI_ASISTENCIA_ACT
ADD CONSTRAINT FK_JDI_ASISTENCIA_ACTIVID FOREIGN KEY (ID_ACT) REFERENCES JDI_ACTIVIDADES (ID_ACT) ON DELETE CASCADE;

ALTER TABLE JDI_ASISTENCIA_ACT
ADD CONSTRAINT FK_JDI_ASISTENCIA_JDI_DOCENTES FOREIGN KEY (DNI) REFERENCES JDI_DOCENTES (DNI) ON DELETE SET NULL;