CREATE TABLE HP_PACIENTES(
    DNI                 VARCHAR2(9),
    NOMBRE              VARCHAR2(200),
    APELLIDOS           VARCHAR2(200),
    DIRECCION           VARCHAR2(500),
    CP                  VARCHAR2(5),
    POBLACION           VARCHAR2(30),
    PROVINCIA           VARCHAR2(30),
    FECHA_NACIMIENTO    DATE,
    TELEFONO            NUMBER(9),
    
    CONSTRAINT PK_PACIENTES PRIMARY KEY (DNI)
);

CREATE TABLE HP_ASEGURADORAS(
    CIF                 VARCHAR2(9),
    NOMBRE              VARCHAR2(200),
    DIRECCION           VARCHAR2(300),
    WEB                 VARCHAR2(500),
    TELEFONO            NUMBER(9),
    
    CONSTRAINT PK_ASEGURADORAS PRIMARY KEY (CIF)
);

CREATE TABLE HP_CONSULTAS(
    DNI                 VARCHAR2(9),
    FECHA_CONSULTA      DATE,
    DIAGNOSTICO         CLOB,
    
    CONSTRAINT PK_CONSULTAS PRIMARY KEY (DNI, FECHA_CONSULTA)
);

CREATE TABLE HP_PACIENTE_ASEGURADORA(
    DNI                 VARCHAR2(9),
    CIF                 VARCHAR2(9),
    PRECIO_UNITARIO     NUMBER(6,2),
    
    CONSTRAINT PK_PACIENTE_ASE PRIMARY KEY (DNI)
);

CREATE TABLE HP_PACIENTES_VIP(
    DNI                 VARCHAR2(9),
    NOMBRE              VARCHAR2(200),
    APELLIDOS           VARCHAR2(200),
    DIRECCION           VARCHAR2(500),
    CP                  VARCHAR2(5),
    POBLACION           VARCHAR2(30),
    PROVINCIA           VARCHAR2(30),
    FECHA_NACIMIENTO    DATE,
    TELEFONO            NUMBER(9),
    
    CONSTRAINT PK_PACIENTES_VIP PRIMARY KEY (DNI)
);

ALTER TABLE HP_CONSULTAS
ADD CONSTRAINT FK_CONSULTAS_PACIENTES FOREIGN KEY (DNI) REFERENCES HP_PACIENTES;

ALTER TABLE HP_PACIENTE_ASEGURADORA
ADD CONSTRAINT HP_PACIENTE_ASEGURADORA_PAC FOREIGN KEY (DNI) REFERENCES HP_PACIENTES;
ALTER TABLE HP_PACIENTE_ASEGURADORA
ADD CONSTRAINT HP_PACIENTE_ASEGURADORA_ASG FOREIGN KEY (CIF) REFERENCES HP_ASEGURADORAS;

INSERT INTO HP_PACIENTES (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO)
VALUES ('11111111A', 'JOSE ANTONIO', 'PEREZ GOMEZ', TO_DATE('01/01/1989', ('DD/MM/YYYY')), 11111111);
INSERT INTO HP_CONSULTAS (DNI, FECHA_CONSULTA)
VALUES ('11111111A', TO_DATE('25/03/2014 16:30',('DD/MM/YYYY HH24:MI')));
UPDATE HP_CONSULTAS 
SET DIAGNOSTICO = 'Disfunción en la cadera. Se le recomienda realizar una resonancia magnética.'
WHERE DNI = '11111111A' AND FECHA_CONSULTA = TO_DATE('25/03/2014 16:30',('DD/MM/YYYY HH24:MI'));

INSERT INTO HP_PACIENTES (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO)
VALUES ('22222222B', 'ANA MARIA', 'VELASCO SANCHEZ', TO_DATE('02/02/1989', ('DD/MM/YYYY')), 222222222);
INSERT INTO HP_CONSULTAS (DNI, FECHA_CONSULTA)
VALUES ('22222222B', TO_DATE('25/03/2014 17:00',('DD/MM/YYYY HH24:MI')));

INSERT INTO HP_PACIENTES (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO)
VALUES ('33333333C', 'ISABEL', 'GARCIA MARTINEZ', TO_DATE('03/03/1989', ('DD/MM/YYYY')), 333333333);
INSERT INTO HP_CONSULTAS (DNI, FECHA_CONSULTA)
VALUES ('33333333C', TO_DATE('25/03/2013 17:30',('DD/MM/YYYY HH24:MI')));
UPDATE HP_CONSULTAS
SET FECHA_CONSULTA = NEXT_DAY((TO_DATE('25/03/2013 14:00','DD/MM/YYYY HH24:MI')), 'LUNES')
WHERE DNI = '33333333C' AND FECHA_CONSULTA = TO_DATE('25/03/2013 17:30',('DD/MM/YYYY HH24:MI'));

INSERT INTO HP_PACIENTES (DNI, NOMBRE, APELLIDOS)
VALUES ('66666666F', 'JUAN', 'PEREZ CAYUELA');



--DATOS DE EJEMPLO PARA VIP
INSERT INTO HP_ASEGURADORAS (CIF, NOMBRE)
VALUES ('55555555E', 'ADESLAS');

INSERT INTO HP_PACIENTES_VIP (DNI, NOMBRE, APELLIDOS, FECHA_NACIMIENTO, TELEFONO)
VALUES ('44444444D', 'MANUEL', 'FERNANDEZ ARJONA', TO_DATE('27/01/1989',('DD/MM/YYYY')), 444444444);

INSERT INTO HP_PACIENTE_ASEGURADORA (DNI, CIF, PRECIO_UNITARIO)
VALUES ('44444444D', '55555555E', 200);
--NO HE SIDO CAPAZ DE RESOLVER EL ERROR QUE APARECE

DELETE FROM HP_PACIENTES
WHERE DNI ='66666666F';


/*
DROP TABLE HP_PACIENTES;
DROP TABLE HP_ASEGURADORAS;
DROP TABLE HP_CONSULTAS;
DROP TABLE HP_PACIENTE_ASEGURADORA;
*/