CREATE TABLE LIBROS(
    ISBN                VARCHAR2(13),
    TITULO              VARCHAR2(50),
    DNI_AUTOR           VARCHAR2(9),
    COD_GENERO          NUMBER(3),
    COD_EDITORIAL       NUMBER(10),
    CONSTRAINT PK_LIBROS PRIMARY KEY (ISBN),
    CONSTRAINT NN_LIBROS_TITULO CHECK (TITULO IS NOT NULL),
    CONSTRAINT NN_LIBROS_DNI_AUTOR CHECK (DNI_AUTOR IS NOT NULL),

);