CREATE TABLE EMP_EMPLEADOS(
    DNI                     VARCHAR2(9),
    NOMBRE                  VARCHAR(20),
    APELLIDO1               VARCHAR(20),
    APELLIDO2               VARCHAR(20),
    SUELDO                  NUMBER(7),
    NUM_D                   NUMBER(5),
    DNI_SUPERVISOR          VARCHAR(9),
    
    CONSTRAINT PK_EMP_EMPLEADOS PRIMARY KEY (DNI)
);

CREATE TABLE EMP_DEPARTAMENTOS(
    NUM_DEPT                NUMBER(5),
    NOMBRE_DEPT             VARCHAR2(15),
    DNI_JEFE                VARCHAR2(9),
    FECHA_CREACION          DATE,
    
    CONSTRAINT PK_EMP_DEPARTAMENTOS PRIMARY KEY (NUM_DEPT)
);

CREATE TABLE EMP_PROYECTOS(
    NUM_P                   NUMBER(3),
    NOMBRE                  VARCHAR(30),
    LUGAR                   VARCHAR(50),
    NUM_D                   NUMBER(5),
    
    CONSTRAINT PK_EMP_PROYECTOS PRIMARY KEY (NUM_P)
);

CREATE TABLE EMP_TRABAJA_EN(
    DNI                     VARCHAR2(9),
    NUM_P                   NUMBER(3),
    NUM_HORAS               NUMBER,
    
    CONSTRAINT PK_EMP_TRABAJA_EN PRIMARY KEY (DNI, NUM_P)
);

ALTER TABLE EMP_EMPLEADOS
ADD CONSTRAINT FK_EMP_EMPLEADOS FOREIGN KEY (DNI_SUPERVISOR) REFERENCES EMP_EMPLEADOS (DNI);

ALTER TABLE EMP_EMPLEADOS
ADD CONSTRAINT FK_EMP_EMPL_DEPA FOREIGN KEY (NUM_D) REFERENCES EMP_DEPARTAMENTOS (NUM_DEPT);

ALTER TABLE EMP_DEPARTAMENTOS
ADD CONSTRAINT FK_EMP_DEPA_EMPL FOREIGN KEY (DNI_JEFE) REFERENCES EMP_EMPLEADOS (DNI);

ALTER TABLE EMP_PROYECTOS
ADD CONSTRAINT FK_EMP_PROY_DEPA FOREIGN KEY (NUM_D) REFERENCES EMP_DEPARTAMENTOS (NUM_DEPT);

ALTER TABLE EMP_TRABAJA_EN
ADD CONSTRAINT FK_EMP_TR_PROY FOREIGN KEY (NUM_P) REFERENCES EMP_PROYECTOS (NUM_P);

ALTER TABLE EMP_TRABAJA_EN
ADD CONSTRAINT FK_EMP_TR_EMPL FOREIGN KEY (DNI) REFERENCES EMP_EMPLEADOS (DNI);
/*
DROP TABLE EMP_EMPLEADOS;
DROP TABLE EMP_DEPARTAMENTOS;
DROP TABLE EMP_PROYECTOS;
DROP TABLE EMP_TRABAJA_EN;