SET SERVEROUTPUT ON;

CREATE  OR REPLACE PROCEDURE EMP_SUBORDINADOS(
    EMP_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
IS
    CURSOR MFA_C1 IS
    SELECT *
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID;
    
    DATOS_JEFE EMPLOYEES%ROWTYPE;
BEGIN

    SELECT * INTO DATOS_JEFE
    FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;
    
    DBMS.OUTPUT.PUT_LINE('DATOS DEL JEFE -->' || ' ' || DATOS_JEFE.FIRST_NAME || ' ' || DATOS_JEFE.LAST_NAME);
    
    FOR V_REG IN C1 LOOP
    DBMS.OUTPUT.PUT_LINE(V_REG.FIRST_NAME || ' ' || V_REG.LAST_NAME);
    END LOOP;
    
    
END;
    