SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE INSERTA_DEPARTAMENTO
(DEPARTMENT_NAME HR.DEPARTMENTS.DEPARTMENT_NAME%TYPE , MANAGER_ID DEPARTMENTS.MANAGER_ID%TYPE , LOCATION_ID DEPARTMENTS.LOCATION_ID%TYPE)
IS
IDD NUMBER;
BEGIN

SELECT MAX(DEPARTMENT_ID) INTO IDD FROM DEPARTMENTS;
    IDD:= TRUNC(IDD-1)+10;
    DBMS_OUTPUT.PUT_LINE(IDD);
    INSERT INTO DEPARTMENTS 
    VALUES(IDD,DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID);
END;

BEGIN
    INSERTA_DEPARTAMENTO('DepartN', 100, 1700);
END;

