SET SERVEROUTPUT ON;
--PARA QUE IMPRIMA

BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;


--DECLARAR UNA VARIABLE
DECLARE
    n NUMBER :=2;
    n1 NUMBER :=3;
    n2 NUMBER;
    pi CONSTANT NUMBER(9,7):=3.1415927;
BEGIN
    n2 := n*n1;
    DBMS_OUTPUT.PUT_LINE('El valor de n2 es '|| n2);
    DBMS_OUTPUT.PUT_LINE('Pi es igual a '||pi);
END;


--TIPOS DE DATOS
DECLARE
    N1 PLS_INTEGER;
    N2 CONSTANT PLS_INTEGER := 12;
    FEC_NAC DATE;
    DIAS PLS_INTEGER;
    EDAD_JUV CONSTANT PLS_INTEGER := 70;
    EDAD PLS_INTEGER;
    ANYOS PLS_INTEGER;
BEGIN
    FEC_NAC := TO_DATE('05/10/2001','DD/MM/YYYY');
    DIAS := SYSDATE - fec_nac;
    N1 :=18;
    EDAD := MONTHS_BETWEEN(SYSDATE, FEC_NAC)/12;
    ANYOS := EDAD_JUV - EDAD;
    DBMS_OUTPUT.PUT_LINE('El numero de meses que llevo vivo el aproximadamente '||n1*n2);
    DBMS_OUTPUT.PUT_LINE('Los dias que llevo vivo son '||DIAS);
    DBMS_OUTPUT.PUT_LINE('Los meses que me quedan para juvilarme son ' ||ANYOS);
END;


--COPIAR TIPOS DE DATOS
CREATE TABLE PRESONA(
    DNI                 NUMBER(10),
    NOMBRE              VARCHAR2(25),
    APELLIDOS           VARCHAR2(25),
    FECHA_NAC           DATE,
    
    CONSTRAINT PK_NFX_CLIENTES PRIMARY KEY (DNI)  
);
DECLARE
    V_DNI PRESONA.DNI%TYPE;
    VAR1 PLS_INTEGER;
    VAR2 VAR1%TYPE;
BEGIN
    V_DNI := '123456789T';
END;

/*
PODEMOS DAR TIPO DE 3 FORMAS

1 DIRECTAMENTE CON  V1 PLS_INTEGER;

2 ATRAVES DE UNA VARIABLE  V2 V1%TYPE;

3 ATRAVES DEL TIPO DE DATO DE UNA COLUMNA DE UNA TABLA  V3 TABLA.COL%TYPE;
*/

DECLARE
    NUMERO PLS_INTEGER;
BEGIN
    NUMERO := MOD(ABS(DBMS_RANDOM.RANDOM),31)+30;
    DBMS_OUTPUT.PUT_LINE('EL NUMERO ES: ' ||numero);
END;
